# example config
{
  # if internal has dirs that are not present in "Layers" key below, report error
  "ReportDirsWithoutAssignedLayer": true,

  # can only import from same layer and one layer directly above. report error if using storage from ui for example
  "OnlyAdjacent": false,

  # list of dirs from high abstraction to low level. low can depend on high
  "Layers": [
    "high",
    "low",
    # main is on layer 0 implicitly
  ]
}